export const QuizCategories: { [key: number]: string } = {
    9: 'General Knowledge',
    10: 'Ent.: Books',
    11: 'Ent.: Film',
    12: 'Ent.: Music',
    13: 'Ent.: Musicals & Theatres',
    14: 'Ent.: Television',
    15: 'Ent.: Video Games',
    16: 'Ent.: Board Games',
    17: 'Sci & Nature',
    18: 'Sci: Comp',
    19: 'Sci: Math',
    20: 'Myth',
    21: 'Sports',
    22: 'Geography',
    23: 'History',
    24: 'Politics',
    25: 'Art',
    26: 'Celebrities',
    27: 'Animals',
    28: 'Vehicles',
    29: 'Ent: Comics',
    30: 'Science: Gadgets',
    31: 'Ent: Japanese Anime & Manga',
    32: 'Ent: Cartoon & Animations',
    33: 'Any'
};